# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_programdepartmentrelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='programDepartmentRelationship',
        ),
        migrations.AddField(
            model_name='post',
            name='programDepartmentRelationship',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Program_Department_Relationship'),
        ),
    ]
