# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='field10',
        ),
        migrations.RemoveField(
            model_name='post',
            name='field6',
        ),
        migrations.RemoveField(
            model_name='post',
            name='field7',
        ),
        migrations.RemoveField(
            model_name='post',
            name='field8',
        ),
        migrations.RemoveField(
            model_name='post',
            name='field9',
        ),
    ]
