# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20160922_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptt_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200)),
                ('value', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Program_Department_Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(default='', max_length=100)),
                ('deptt', models.CharField(default='', max_length=100)),
                ('deptt_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Department')),
                ('program_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Program')),
            ],
        ),
    ]
